# Authentication

# Token authentication

# check auth
vault auth list

# Create a new token
# This token is a child of the root token, and
# by default, it inherits the policies from its parent
vault token create

# help on token
vault auth help token

# Token is the core authentication method.
# You can use the generated token to login with Vault.
vault login s.Wnhp8nYdfucLkGULfgAt7FXA
# Create another token
vault token create

# Revoke the first token you created
vault token revoke s.Wnhp8nYdfucLkGULfgAt7FXA
# * permission denied
vault login s.Wnhp8nYdfucLkGULfgAt7FXA

# GitHub authentication

# export root token (optional-if * permission denied)
export VAULT_TOKEN=s.DZEXwshb1fj1tkXa29ASJIkc

# Enable the GitHub auth method
vault auth enable github

# This auth method requires that you set a GitHub organization in the configuration.
# A GitHub organization maintains a list of users which you are allowing to authenticate with Vault.
# Set the organization for the github authentication
vault write auth/github/config/ organization=hashicorp
vault write auth/github/config/ organization=vaultlearn

# GitHub organizations can define teams. Each team may have access to different
# actions across all the repositories that the organization maintains.
# These teams may also need access to specific secrets within Vault.
# Configure the GitHub engineering team authentication to be granted the default and applications policies.
vault write auth/github/map/teams/engineering value=default,applications
vault write auth/github/map/teams/engineering value=default,applications

# Display all the authentication methods that Vault has enabled
vault auth list

# auth help for github
vault auth help github

# VAULT_TOKEN environment variable will take precedence over any token you obtain from Vault.
# Unset the VAULT_TOKEN environment variable
unset VAULT_TOKEN

# Attempt to login with the github auth method.
# When the GitHub personal access token is not provided to the command the Vault CLI prompts the operator.
vault login -method=github

# Log back in with the root token
vault login root

# Revoke all tokens generated the github auth method
vault token revoke -mode path auth/github

# Disable the github auth method
# All tokens generated by logins using this authentication method are revoked.
vault auth disable github
