# ALS Ice Bucket Challenge

#######################################################################################################################
#
#   The ALS Ice Bucket Challenge has become viral on internet these days. Many people are coming forward for the
#   noble cause, making a video of pouring icy cold water on them and putting them on the web. If they fail to do so,
#   they must donate some money to charity. But the funny part is that you cannot do the task on your own; you do
#   it only when you are nominated by someone else. So are YOU ready for the challenge ??
#   Now the ALS Challenge is about to enter our city, the Hacker's City. There are N2 people in the city and it is
#   very densely populated. The city is therefore build like a grid of size N x N with one person living in each
#   of the cells. Because of such tight formation, people are only friends with the ones living adjacent to them
#   (there can be at most 8 people living adjacent to some person in a grid). Also it must be noted that there are
#   some celebrities (at least one) in the city as well (Yeah!! our city is famous).
#   Initially one person in the Hacker's city receives the challenge from some outside source (it could be anyone).
#   After attempting the challenge, he can nominate the challenge to any of his friend (remember, neighbors are best
#   friends). The city mayor wants each and every celebrity in his city to attempt the challenge. In this way,
#   his smart city would become more famous.
#   Now the real problem starts for the mayor. There is serious water shortage in the city. The celebrities
#   (rich people), have their own water tanks and so there is no problem for them. Other citizens have to purchase
#   the ice bucket. For every person Pij in the city (0  <=  i, j < N), the water department gives them a ice bucket
#   at cost Cij. You need to help the mayor to choose the people such that all the celebrities can complete the task
#   and the overall cost is as small as possible.
#
#   Input & Output:
#   First line of the input contains the number of test cases T. The test cases follow one by one. Each test case
#   starts with a number on a line, N, the size of the city. Then follow N lines with N space separated integers
#   on each of them. These indicate the cost Cij for that specific person. Cij is 0 if the person in a celeb,
#   otherwise it is a positive number : the cost of the ice bucket for that person.
#   The first line of your output for every test case should contain the number of people, (K), you believe will
#   attempt the challenge so that all celebrities get nominated. Each of the next K lines contain two space
#   separated numbers (i j) (zero based indexing), the location of the person.
#
#   Constraints:
#   T = 13
#   N  <=  100
#   0  <=  Cij  <=  10000
#
#   Validity:
#   Your solution will be valid if each of the celebrity gets a chance to be nominated for the challenge.
#   Also K should be between 0 and N2 inclusive. All the locations you give should be between 0 and N (exclusive).
#   There must not be any repeated cells. If these conditions are not met, you will receive a wrong answer verdict.
#
#   Scoring:
#   If your answer is valid, your score is calculated as follows. For each of the bucket, its cost is squared.
#   The sum of all these K squares are added up. Your goal should be to minimize this total.
#
#   Test case generation:
#   3 test cases in every file are manual. There is no definite algorithm for that. The other 10 test cases are
#   generated by the following algorithm.
#       - N is fixed to be 100.
#       - The number of celebs are chosen as a uniform random number between 10 and 100. From now on, whenever
#           it is said chosen it should be assumed it is chosen randomly and uniformly.
#       - Now we need to place the celebs. The grid is viewed as a cyclic single dimension array, by appending
#           rows next to each other. A number is chosen in the range [1, 1000] (S). We need to skip S cells.
#           If a cell already has a celeb it is ignored. Otherwise S is decremented by 1. Finally, when S = 0
#           we assign the celeb to that particular cell.
#       - All unassigned cells are filled with values chosen from the range [1, 10000].
#
#   SAMPLE INPUT
#   1
#   4
#   3 5 7 0
#   0 8 2 3
#   10 1 9 3
#   4 7 4 0
#
#   SAMPLE OUTPUT
#   3
#   0 1
#   1 2
#   2 3
#
#   Explanation
#   There are 4 x 4 cells. The celebs are in the cells = {(1, 0), (0, 3), (3, 3)}. Initially (0, 1) will receive
#   the challenge from outside sources. He will pass it to (1, 0) and (1, 2). (1, 2) will pass it to (0, 3)
#   and (2, 3). Finally (2, 3) will nominate (3, 3). Thus all celebs are covered. The cost of buckets are {5, 2, 3}.
#   Hence the score is 25 + 4 + 9 = 38.
#   Note that this is not the best score. You can achieve better results for this test case. However,
#   your answer is still correct.
#
#######################################################################################################################
