# base image
FROM ubuntu

# do image configuration
RUN /bin/bash -c 'echo This would generally be apt-get or other system configuration.'
ENV myCustomEnvVar="This is a sample." \
    otherEnvVar="This is also a sample."
