apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod3
  name: nginx-pod3
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod3
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
