# Dockerfile

################################################################################
# Ubuntu based Hello world container

FROM ubuntu:15.04
MAINTAINER sagarnikam123@gmail.com
RUN apt-get update
CMD ["echo", "Hello World"]

################################################################################
