apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  namespace: namespace-1
  labels:
    name: secret-test-pod
spec:
  containers:
  - name: secret-test-pod
    image: registry.k8s.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: podsecret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: podsecret
            key: password
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
